### ISSUE TITLE
tf record files are not generating

### ISSUE THREAD

**Issue by sowmyakavali** [prabhakar-sivanesan/Custom-keypoint-detection#2]
I ran this command 

`%cd "/content/TensorFlow/models/research/object_detection"
!python dataset_tools/create_coco_tf_record.py --train_image_dir "/content/Custom-keypoint-detection/dataset/images" \
--test_image_dir "/content/Custom-keypoint-detection/dataset/images" \
--val_image_dir "/content/Custom-keypoint-detection/dataset/images" \
--train_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/train.json" \
--testdev_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/val.json" \
--val_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/val.json" \
--train_keypoint_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/train.json" \
--val_keypoint_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/val.json" \
--output_dir "/content/custom_keypoint_detection/dataset/tfrecord/"`

It is not generating .record files but giving this output

`/content/TensorFlow/models/research/object_detection
I0708 07:55:13.186966 139704579422080 create_coco_tf_record.py:401] Found groundtruth annotations. Building annotations index.
I0708 07:55:13.187198 139704579422080 create_coco_tf_record.py:414] 0 images are missing annotations.
I0708 07:55:13.189434 139704579422080 create_coco_tf_record.py:443] On image 0 of 44
I0708 07:55:13.236015 139704579422080 create_coco_tf_record.py:470] Finished writing, skipped 0 annotations.
I0708 07:55:13.236133 139704579422080 create_coco_tf_record.py:473] Finished writing, skipped 0 keypoint annotations.
I0708 07:55:13.241920 139704579422080 create_coco_tf_record.py:401] Found groundtruth annotations. Building annotations index.
I0708 07:55:13.242027 139704579422080 create_coco_tf_record.py:414] 0 images are missing annotations.
I0708 07:55:13.242739 139704579422080 create_coco_tf_record.py:443] On image 0 of 11
I0708 07:55:13.252087 139704579422080 create_coco_tf_record.py:470] Finished writing, skipped 0 annotations.
I0708 07:55:13.252181 139704579422080 create_coco_tf_record.py:473] Finished writing, skipped 0 keypoint annotations.
I0708 07:55:13.255093 139704579422080 create_coco_tf_record.py:401] Found groundtruth annotations. Building annotations index.
I0708 07:55:13.255200 139704579422080 create_coco_tf_record.py:414] 0 images are missing annotations.
I0708 07:55:13.255263 139704579422080 create_coco_tf_record.py:443] On image 0 of 11
I0708 07:55:13.263692 139704579422080 create_coco_tf_record.py:470] Finished writing, skipped 0 annotations.`

can you please tell what  wrong is there in code?

**Comment by sowmyakavali** [comment]
> I ran this command
> 
> `%cd "/content/TensorFlow/models/research/object_detection" !python dataset_tools/create_coco_tf_record.py --train_image_dir "/content/Custom-keypoint-detection/dataset/images" \ --test_image_dir "/content/Custom-keypoint-detection/dataset/images" \ --val_image_dir "/content/Custom-keypoint-detection/dataset/images" \ --train_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/train.json" \ --testdev_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/val.json" \ --val_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/val.json" \ --train_keypoint_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/train.json" \ --val_keypoint_annotations_file "/content/Custom-keypoint-detection/dataset/annotations/val.json" \ --output_dir "/content/custom_keypoint_detection/dataset/tfrecord/"`
> 
> It is not generating .record files but giving this output
> 
> `/content/TensorFlow/models/research/object_detection I0708 07:55:13.186966 139704579422080 create_coco_tf_record.py:401] Found groundtruth annotations. Building annotations index. I0708 07:55:13.187198 139704579422080 create_coco_tf_record.py:414] 0 images are missing annotations. I0708 07:55:13.189434 139704579422080 create_coco_tf_record.py:443] On image 0 of 44 I0708 07:55:13.236015 139704579422080 create_coco_tf_record.py:470] Finished writing, skipped 0 annotations. I0708 07:55:13.236133 139704579422080 create_coco_tf_record.py:473] Finished writing, skipped 0 keypoint annotations. I0708 07:55:13.241920 139704579422080 create_coco_tf_record.py:401] Found groundtruth annotations. Building annotations index. I0708 07:55:13.242027 139704579422080 create_coco_tf_record.py:414] 0 images are missing annotations. I0708 07:55:13.242739 139704579422080 create_coco_tf_record.py:443] On image 0 of 11 I0708 07:55:13.252087 139704579422080 create_coco_tf_record.py:470] Finished writing, skipped 0 annotations. I0708 07:55:13.252181 139704579422080 create_coco_tf_record.py:473] Finished writing, skipped 0 keypoint annotations. I0708 07:55:13.255093 139704579422080 create_coco_tf_record.py:401] Found groundtruth annotations. Building annotations index. I0708 07:55:13.255200 139704579422080 create_coco_tf_record.py:414] 0 images are missing annotations. I0708 07:55:13.255263 139704579422080 create_coco_tf_record.py:443] On image 0 of 11 I0708 07:55:13.263692 139704579422080 create_coco_tf_record.py:470] Finished writing, skipped 0 annotations.`
> 
> can you please tell what wrong is there in code?


I came to know that it is generating .record files for each annotation file but i have given wrong path. The code working perfectly. It was my mistake.

**Comment by prabhakar-sivanesan** [comment]
Thanks for letting know. Please raise issues if there's any in the future. I will close this for now.
